Provide syscall wrappers for `mmap` and `munmap`
libunwind/libunwind pull request #486
Opened 2023-03-30 20:26 UTC by bertwesarg

These functions are assumed to be direct wrappers to the syscalls, but in the past (see Open MPI) and also now (see UCX) runtimes do intercept these functions and do AS-unsafe stuff inside there runtimes. Hence provide internal syscall wrappers for these functions to improve AS-safety.

2023-03-30 20:40 UTC, bregma commented
We have to support targets other than GNU/Linux. Embedded GNU libc calls with Linux kernel bindings is not going to fly.

2023-03-31 07:00 UTC, bertwesarg commented
> We have to support targets other than GNU/Linux. Embedded GNU libc calls with Linux kernel bindings is not going to fly.

please point me how to make this portable then. thanks

2023-04-02 14:07 UTC, bregma requested changes
Include file needs #ifdefing but otherwise looks good.

2023-04-02 14:07 UTC, bregma commented on include/libunwind_i.h
> +#include <sys/syscall.h>   /* For SYS_xxx definitions */
This non-portable header needs to be surrounded with an `#if defined(HAVE_SYS_SYSCALL_H)`.

2023-04-03 17:33 UTC, merged