Clean ci warnings
libunwind/libunwind pull request #807
Opened 2024-10-03 18:20 UTC by gleocadie

2024-10-09 13:26 UTC, bregma requested changes
Please rework this to use the existing UNUSED decorator.

2024-10-09 13:26 UTC, bregma commented on src/x86/Ginit.c
> +
We already have a macro **`UNUSED`** defined in `compiler.h`.

2024-10-09 13:26 UTC, bregma commented on src/dwarf/Gfde.c
> +      return val == (unw_word_t)(-1);
Yes.

2024-10-09 17:43 UTC, gleocadie commented
> Please rework this to use the existing UNUSED decorator.

Sure.
I put it as Draft for now, because I wanted to see the impact/if it's working and also asking if we already have something.
Thanks for your comment, I'll update my draft.

2025-02-25 20:55 UTC, bregma approved these changes

2025-02-25 20:55 UTC, merged